### ISSUE TITLE
[Editor] Using the SQL Editor

### ISSUE THREAD

**Issue by nicolaslara** [rapidpro/chpro#17]
As Editor, I would update geodatabase for health unit in order to map out indicators then, I upload CSV file with XY coordinates by units. This unit will be related to dataset through unit_id

**Comment by nicolaslara** [comment]
The editor will need permissions to use the SQL editor. ref #13

**Comment by unbracketed** [comment]
When the `Editor` role is initialized, each of the [`sql_lab` role](https://superset.incubator.apache.org/security.html#sql-lab) permissions is copied to it.  Editors are expected to have full access to the SQL Lab feature.
