### ISSUE TITLE
Visual & CSS Bugs to Address

### ISSUE THREAD

**Issue by sodevious** [rapidpro/chpro#31]
|     ✓      |  Issue          | Reference  |
|:-------------:|-------------| -----|
| **Responsive**     |   |   |
|  ✓  | Phone size: needs padding to left and right | [image](https://user-images.githubusercontent.com/915966/40144582-26516c9c-592d-11e8-87a7-3ab3de397858.png) |
|  ✓  | Tablet size: links collapse earlier so that there is no wrapping      |   [image](https://user-images.githubusercontent.com/915966/40144583-26e62bd4-592d-11e8-8612-d8859ac06bdd.png)|
| **General UI**    |   |   |
|    ✓| Fix this icon which is too far down      |   [image](https://user-images.githubusercontent.com/915966/40144815-d2dbffcc-592d-11e8-977f-c9c8c4361b77.png)|
|  ✓  | Add a container or background color so it's clearer that this is a filter and not random boxes      |   [image](https://user-images.githubusercontent.com/915966/40145081-8b083340-592e-11e8-9f1f-49f3f4e30059.png)|
|  ✓   | show database view: well + list is broken      |   [image](https://user-images.githubusercontent.com/915966/40145152-c7fd3b56-592e-11e8-96b2-e325f5cec049.png)|
|   ✓ | list pages off when no "Add" button (see if we can do this without absolute positioning or move the + button elsewhere)      |   [image](https://user-images.githubusercontent.com/915966/40145224-0ab07382-592f-11e8-8db5-8881bc1d6a0f.png)|
|    ✓ | user statistics: well is broken and content is hidden      |   [image](https://user-images.githubusercontent.com/915966/40145273-323b2f50-592f-11e8-9e28-0b33295dbcf4.pn)|
|  ✓    | sql lab: fix this icon on hover      |   [image](https://user-images.githubusercontent.com/915966/40145380-8a5ed434-592f-11e8-83e7-50db07e53d2c.png)|
|  ✓    | sql lab: see if we can use the + button without the circle and make it slightly more prominent      |   [image](https://user-images.githubusercontent.com/915966/40145382-8ad9f880-592f-11e8-82a4-a2b65afd4dbe.png)|
| ✓    | edit dashboard properties table broken    |   [image](https://user-images.githubusercontent.com/915966/40145449-d2462f18-592f-11e8-88b5-9b220391dba8.png)|
|  ✓  | dashboard: lighten up these dropshadows    |   [image](https://user-images.githubusercontent.com/915966/40145464-e7b8506a-592f-11e8-9be4-3bb4373d6c11.png)|
| ✓   | better spinning refresh icon style    |   [image](https://user-images.githubusercontent.com/915966/40145499-1a6d436c-5930-11e8-973a-e2cd379b1c66.png)|
|  ✓  | address explore chart spacing?    |   [image](https://user-images.githubusercontent.com/915966/40145537-45a80bca-5930-11e8-9cee-ae7cc7def0f5.png)|

**Comment by nicolaslara** [comment]
> address explore chart spacing?

That's not spacing. There's a panel missing in the left hand side. Maybe due to permissions. I'll investigate

**Comment by nicolaslara** [comment]
Looked at the "chart spacing" issue again. The controls are there, but the styles are hiding them. @sodevious can you make this the top priority? that way they can keep using the test dashboard
