### ISSUE TITLE
[Editor] Adding a new DB to superset

### ISSUE THREAD

**Issue by nicolaslara** [rapidpro/chpro#8]
As Editor, I would like to add a new database in superset.

**Comment by nicolaslara** [comment]
This was originally planned to be done by an administrator (i.e. by manually running commands on the console). 

We can create a custom view to handle DB creation

**Comment by vturmine** [comment]
@nicolaslara the best would be to have a simple interface for that but if you have a "how to do" that would be ok.

**Comment by jessiofhall** [comment]
@nicolaslara will you confirm @vturmine's last comment?
