### ISSUE TITLE
Rapid pro data Import/Export

### ISSUE THREAD

**Issue by nicolaslara** [rapidpro/chpro#9]
This is one of the options for data import after creating the db (#8 )

--
From the Use Cases:

I collect data through RapidPro and export in real time data to an external DB (MySQL or Postgresql) for displaying in realtime collected data

**Comment by nicolaslara** [comment]
We will probably need clarification on the details here but, as I understand it, the goal is to have rapid pro data be loaded to the dashboard in real time. 

* Do you have a sample of the data that would be imported from rapid pro? 
* How do the api endpoints look like? 
 * Is this a process that can be done in a _pull_ manner? (i.e. the rapid pro API is publicly available and the dashboard can periodically fetch from it)

**Comment by scampo** [comment]
@nicolaslara yes, this is a key component of the overall project. This should've been clear from the outset from @vturmine. The RapidPro API explorer is here: https://rapidpro.io/api/v2/explorer/

**Comment by ewheeler** [comment]
also python client library is here https://github.com/rapidpro/rapidpro-python

additionally, our rapidpro data warehouse has code for pulling/syncing data from rapidpro instances (and exposes an API compatible with rapidpro's v2 that also has some additional params)
https://github.com/rapidpro/data_api

**Comment by nicolaslara** [comment]
Thanks for the info! I'll move this into the backlog. 

@ewheeler Could you provide me with an api key for testing?

**Comment by nicolaslara** [comment]
Got an API key from @vturmine. Should be enough to start developing this.

**Comment by nicolaslara** [comment]
We should create a CLI command for the import and setup a cron job for it to run periodically

**Comment by nicolaslara** [comment]
@vturmine I have the initial code to import Runs from RapidPro, but we may need to discuss what data you want to display to make a decision on what else to import and how to model it. 

I can't keep moving forward with the import until we make a decision on this

**Comment by nicolaslara** [comment]
@vturmine When you can, please get me the data we discussed on the call so I can move forward on this (I think it was the data related to Pakistan)

**Comment by scampo** [comment]
we're chasing Elliot for it. Sorry for delay!

-----------------------------------
*Stuart Campo*
+1.802.249.8233 (U.S.)
+31.626.233.230 (Netherlands)
skype: stuart.campo
twitter: @stucampo

**Comment by nicolaslara** [comment]
As per our discussions on the call on May 17th, this will be handled by creating a generic command that can be extended for the specific use cases needed on each implementation.

I will convert the command into a generic one and provide some documentation on how to extend it,
